import mongoose from "mongoose";

const newregistrationSchema = new mongoose.Schema({


    StudentClass: { type: String },
    studentpic: { type: String },
    firstName: { type: String },
    midName: { type: String },
    lastName: { type: String },
    gender: { type: String },
    dob: { type: String },
    nationality: { type: String },
    category: { type: String },
    subCategory: { type: String },
    quota: { type: String },
    motherTongue: { type: String },
    religion: { type: String },
    email: { type: String },
    phone: { type: String },
    altphone: { type: String },
    aadhar: { type: String },
    bloodGroup: { type: String },


    fatherPic: { type: String },
    fatherFirstName: { type: String },
    fatherMidName: { type: String },
    fatherLastName: { type: String },
    fatherPhone: { type: String },
    fatherEmail: { type: String },
    fatherOccupation: { type: String },
    fatherOfficeAddress: { type: String },
    fatherQualification: { type: String },
    fatherCollegeName: { type: String },
    fatherCollegeAddress: { type: String },
    fatherGraduationYear: { type: String },
    fatherGraduationCertificate: { type: String },

    motherPic: { type: String },
    motherFirstName: { type: String },
    motherMidName: { type: String },
    motherLastName: { type: String },
    motherPhone: { type: String },
    motherEmail: { type: String },
    motherOccupation: { type: String },
    motherOfficeAddress: { type: String },
    motherQualification: { type: String },
    motherCollegeName: { type: String },
    motherCollegeAddress: { type: String },
    motherGraduationYear: { type: String },
    motherGraduationCertificate: { type: String },

    guardianPic: { type: String },
    guardianFirstName: { type: String },
    guardianMidName: { type: String },
    guardianLastName: { type: String },
    guardianPhone: { type: String },
    guardianEmail: { type: String },
    guardianRelation: { type: String },
    guardianOccupation: { type: String },
    guardianOfficeAddress: { type: String },
    guardianQualification: { type: String },
    guardianCollegeName: { type: String },
    guardianCollegeAddress: { type: String },
    guardianGraduationYear: { type: String },
    guardianGraduationCertificate: { type: String },

    currentHouseNo: { type: String },
    currentLocality: { type: String },
    currentDistrict: { type: String },
    currentCity: { type: String },
    currentState: { type: String },
    currentPinCode: { type: String },
    currentCountry: { type: String },

    permanentHouseNo: { type: String },
    permanentLocality: { type: String },
    permanentDistrict: { type: String },
    permanentCity: { type: String },
    permanentState: { type: String },
    permanentPinCode: { type: String },
    permanentCountry: { type: String },


    previousSchoolLastClass: { type: String },
    previousSchoolName: { type: String },
    previousSchoolLocation: { type: String },
    previousSchoolLeavingYear: { type: String },
    previousSchoolLastClassMarksheet: { type: String },
    previousSchoolTransferCertificate: { type: String },


})

export const NewRegistration = mongoose.model("NewRegistration", newregistrationSchema)